### ISSUE TITLE
Google Chrome 54 and up - Sliding problem and content not shown

### ISSUE THREAD

**Issue by qbussrl** [iliketomatoes/tabellajs#4]
http://www.tlara.it/it/appartamenti/prezzi-e-condizioni-di-soggiorno
As you can see on the page when you scroll with the price arrow right then the prices are not shown.
This happens also on your official DEMO example.

Where is the problem?

**Comment by iliketomatoes** [comment]
I'm investigating the problem.

**Comment by iliketomatoes** [comment]
@qbussrl  Thank you for pointing out the bug.

With the latest release it has been fixed.  Following your hilightings I have fixed some other related issues. Enjoy it.
